### ISSUE TITLE
Java class naming and structuring

### ISSUE THREAD

**Issue by murjam** [Tarvo-Tammejuur/java_tehnoloogiad#1]
Always - at least without having a good reason to do otherwise - try to avoid underscore in the names of Java classes. Use CamelCase for naming Java classes.

Also keep every Java class within a package - this is the only way another program can potentionally point to the class. Usually every project has a root package named by inversed domain name.
http://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html

**Comment by jaaava** [comment]
I can't seem to find any Java classes that have "_" in their name, but yeah, keeping classes in a package is something I struggle with :) I just want to dive into the project and forget about good practices.

**Comment by murjam** [comment]
> I can't seem to find any Java classes that have "_" in their name

`find . -name '*_*.java'`
