### ISSUE TITLE
Use less spaces in HTML

### ISSUE THREAD

**Issue by murjam** [Tarvo-Tammejuur/java_tehnoloogiad#3]
When giving an XML (or HTML) tag some attributes, the code looks a lot cleaner without spaces. Instead of:
`<div id = "noteWrapper">` write `<div id="noteWrapper">`

**Comment by jaaava** [comment]
True, it does look better. IntelliJ thought it would be a good idea. I used format-action shortcut just to indent elements properly. Didn't even realize it added spaces.
 It's not only cleaner, but adds to file size also. Weird, that its IntelliJ's default behaviour.
